/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    'contact-submissions': ContactSubmission;
    'form-configs': FormConfig;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'form-configs': FormConfigsSelect<false> | FormConfigsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    homepage: Homepage;
    'wohnungen-page': WohnungenPage;
    'preise-page': PreisePage;
    'investment-page': InvestmentPage;
    'lage-page': LagePage;
    'kontakt-page': KontaktPage;
    'architektur-page': ArchitekturPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'wohnungen-page': WohnungenPageSelect<false> | WohnungenPageSelect<true>;
    'preise-page': PreisePageSelect<false> | PreisePageSelect<true>;
    'investment-page': InvestmentPageSelect<false> | InvestmentPageSelect<true>;
    'lage-page': LagePageSelect<false> | LagePageSelect<true>;
    'kontakt-page': KontaktPageSelect<false> | KontaktPageSelect<true>;
    'architektur-page': ArchitekturPageSelect<false> | ArchitekturPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  interesse?: string | null;
  nachricht?: string | null;
  expose?: boolean | null;
  /**
   * Antworten auf Felder, die im Backend zum Formular hinzugefügt wurden.
   */
  weitereAngaben?:
    | {
        feld?: string | null;
        wert?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-configs".
 */
export interface FormConfig {
  id: number;
  /**
   * z.B. "Kontaktformular Deutsch"
   */
  name: string;
  /**
   * Interner Bezeichner, z.B. "kontakt"
   */
  formSlug: string;
  sprache?: ('de' | 'en' | 'sr' | 'ru') | null;
  /**
   * Leer lassen = Standard-Adresse aus Umgebungsvariable
   */
  benachrichtigungsEmail?: string | null;
  /**
   * Sendet dem Kunden nach der Formularabsendung automatisch eine Antwort
   */
  autoresponderAktiv?: boolean | null;
  /**
   * Verfügbare Variablen: {{name}}, {{email}}
   */
  autoresponderBetreff?: string | null;
  /**
   * Verfügbare Variablen: {{name}}, {{email}}, {{interesse}}, {{nachricht}}
   */
  autoresponderNachricht?: string | null;
  /**
   * PDF wird als Anhang an die Autoresponder-E-Mail angehängt
   */
  autoresponderAnhang?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'form-configs';
        value: number | FormConfig;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  interesse?: T;
  nachricht?: T;
  expose?: T;
  weitereAngaben?:
    | T
    | {
        feld?: T;
        wert?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-configs_select".
 */
export interface FormConfigsSelect<T extends boolean = true> {
  name?: T;
  formSlug?: T;
  sprache?: T;
  benachrichtigungsEmail?: T;
  autoresponderAktiv?: T;
  autoresponderBetreff?: T;
  autoresponderNachricht?: T;
  autoresponderAnhang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  address?: string | null;
  copyright?: string | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    headline: string;
    subline?: string | null;
    description?: string | null;
    slides?:
      | {
          image: number | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  lage?: {
    headline?: string | null;
    text1?: string | null;
    text2?: string | null;
    gallery?:
      | {
          image: number | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
    distances?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  wohnungen?: {
    headline?: string | null;
    types?:
      | {
          type: string;
          tag?: string | null;
          size?: string | null;
          description?: string | null;
          price?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  investment?: {
    headline?: string | null;
    text?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    badge?: string | null;
  };
  cta?: {
    headline?: string | null;
    description?: string | null;
    note?: string | null;
  };
  kontakt?: {
    email?: string | null;
    whatsapp?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wohnungen-page".
 */
export interface WohnungenPage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  buildingStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  typesSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineLine2?: string | null;
    unitsLabel?: string | null;
    priceLabel?: string | null;
    exampleNote?: string | null;
    ctaLabel?: string | null;
  };
  types?:
    | {
        nr: string;
        type: string;
        tag?: string | null;
        size?: string | null;
        terrace?: string | null;
        units?: string | null;
        price?: string | null;
        layout?: string | null;
        description?: string | null;
        exampleSize?: number | null;
        examplePrice?: number | null;
        floorplan?: (number | null) | Media;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  ausstattungSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    premiumTitle?: string | null;
  };
  premiumPaket?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  interiorImages?:
    | {
        image?: (number | null) | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  gebaeude?: {
    eyebrow?: string | null;
    headline?: string | null;
    image?: (number | null) | Media;
  };
  gebaeudeFeatures?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
    whatsappLabel?: string | null;
    whatsappUrl?: string | null;
    note?: string | null;
  };
  ausstattung?:
    | {
        brand: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preise-page".
 */
export interface PreisePage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    statPrefix?: string | null;
    extraStatValue?: string | null;
    extraStatLabel?: string | null;
  };
  typesSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    highlightLabel?: string | null;
    typeLabelPrefix?: string | null;
    exampleLabel?: string | null;
    exampleNote?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
  };
  includedSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    includedLabel?: string | null;
  };
  paymentSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    amountNote?: string | null;
  };
  nebenkosten?:
    | {
        label: string;
        value: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  beispielSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    rowArea?: string | null;
    rowPricePerSqm?: string | null;
    rowPurchase?: string | null;
    rowExtraCosts?: string | null;
    rowTotal?: string | null;
    extraCostsRate?: number | null;
  };
  cta?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
    whatsappLabel?: string | null;
    whatsappUrl?: string | null;
    note?: string | null;
  };
  types?:
    | {
        nr: string;
        type: string;
        tag?: string | null;
        size?: string | null;
        pricePerSqm?: string | null;
        units?: string | null;
        highlight?: boolean | null;
        exampleSize?: number | null;
        examplePrice?: number | null;
        floorplan?: (number | null) | Media;
        features?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  paymentSteps?:
    | {
        step: string;
        date?: string | null;
        label: string;
        amount: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        label: string;
        included?: boolean | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-page".
 */
export interface InvestmentPage {
  id: number;
  hero?: {
    headline?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  warumMontenegro?: {
    headline?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    vorteile?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  steuerDaten?:
    | {
        label: string;
        value: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  mietRendite?: {
    headline?: string | null;
    purchase?: number | null;
    size?: number | null;
    pricePerSqm?: number | null;
    weeklyRate?: number | null;
    occupancyWeeks?: number | null;
    annualRent?: number | null;
    yield?: number | null;
    appreciationLow?: number | null;
    appreciationHigh?: number | null;
  };
  paymentSteps?:
    | {
        step: string;
        date?: string | null;
        label: string;
        amount: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lage-page".
 */
export interface LagePage {
  id: number;
  hero?: {
    headline?: string | null;
    subline?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    imageAlt?: string | null;
    address?: string | null;
    mapsLabel?: string | null;
    mapsUrl?: string | null;
  };
  erreichbarkeit?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  karte?: {
    image?: (number | null) | Media;
    imageAlt?: string | null;
    badgeTitle?: string | null;
    badgeSubline?: string | null;
    caption?: string | null;
  };
  distances?:
    | {
        place: string;
        distance: string;
        detail?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  highlightsSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
  };
  highlights?:
    | {
        title: string;
        text?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  markt?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    note?: string | null;
  };
  marktPreise?:
    | {
        label: string;
        price: string;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
    whatsappLabel?: string | null;
    whatsappUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontakt-page".
 */
export interface KontaktPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
  };
  info?: {
    email?: string | null;
    telefon?: string | null;
    whatsapp?: string | null;
    adresse?: string | null;
    officeHours?: string | null;
  };
  direktkontakt?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineZweiteZeile?: string | null;
    description?: string | null;
    labelEmail?: string | null;
    labelWhatsapp?: string | null;
    labelAdresse?: string | null;
  };
  exposeTeaser?: {
    eyebrow?: string | null;
    text?: string | null;
  };
  formular?: {
    headline?: string | null;
    subline?: string | null;
    exposeCheckboxTitle?: string | null;
    exposeCheckboxText?: string | null;
    /**
     * Reihenfolge per Drag-and-drop. Felder lassen sich umbenennen, hinzufügen und entfernen. Der technische Name landet so in der E-Mail und in den Anfragen.
     */
    felder?:
      | {
          label: string;
          /**
           * Nur Kleinbuchstaben, ohne Leerzeichen — z. B. budget
           */
          key: string;
          typ: 'text' | 'email' | 'tel' | 'number' | 'textarea' | 'auswahl' | 'dropdown' | 'checkbox';
          breite?: ('voll' | 'halb') | null;
          platzhalter?: string | null;
          optionen?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          pflichtfeld?: boolean | null;
          id?: string | null;
        }[]
      | null;
    datenschutzText?: string | null;
    fehlerText?: string | null;
    buttonSending?: string | null;
    buttonMitExpose?: string | null;
    buttonOhneExpose?: string | null;
    erfolgHeadline?: string | null;
    erfolgText?: string | null;
    erfolgLinkLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "architektur-page".
 */
export interface ArchitekturPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineZweiteZeile?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    architektLabel?: string | null;
    architektName?: string | null;
    architektStudio?: string | null;
  };
  zitat?: {
    text?: string | null;
    textAccent?: string | null;
    autor?: string | null;
  };
  prinzipien?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    items?:
      | {
          nr: string;
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  fassade?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    items?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  materialien?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    items?:
      | {
          name: string;
          use?: string | null;
          detail?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  galerie?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    images?:
      | {
          image?: (number | null) | Media;
          alt?: string | null;
          aspect?: ('tall' | 'wide' | 'square') | null;
          id?: string | null;
        }[]
      | null;
  };
  gebaeude?: {
    eyebrow?: string | null;
    headline?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    features?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
    buttonSecondaryLabel?: string | null;
    buttonSecondaryLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  address?: T;
  copyright?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subline?: T;
        description?: T;
        slides?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  lage?:
    | T
    | {
        headline?: T;
        text1?: T;
        text2?: T;
        gallery?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        distances?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  wohnungen?:
    | T
    | {
        headline?: T;
        types?:
          | T
          | {
              type?: T;
              tag?: T;
              size?: T;
              description?: T;
              price?: T;
              image?: T;
              id?: T;
            };
      };
  investment?:
    | T
    | {
        headline?: T;
        text?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        badge?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        note?: T;
      };
  kontakt?:
    | T
    | {
        email?: T;
        whatsapp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wohnungen-page_select".
 */
export interface WohnungenPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        image?: T;
      };
  buildingStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  typesSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineLine2?: T;
        unitsLabel?: T;
        priceLabel?: T;
        exampleNote?: T;
        ctaLabel?: T;
      };
  types?:
    | T
    | {
        nr?: T;
        type?: T;
        tag?: T;
        size?: T;
        terrace?: T;
        units?: T;
        price?: T;
        layout?: T;
        description?: T;
        exampleSize?: T;
        examplePrice?: T;
        floorplan?: T;
        image?: T;
        id?: T;
      };
  ausstattungSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        premiumTitle?: T;
      };
  premiumPaket?:
    | T
    | {
        label?: T;
        id?: T;
      };
  interiorImages?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  gebaeude?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        image?: T;
      };
  gebaeudeFeatures?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        buttonLabel?: T;
        buttonLink?: T;
        whatsappLabel?: T;
        whatsappUrl?: T;
        note?: T;
      };
  ausstattung?:
    | T
    | {
        brand?: T;
        label?: T;
        id?: T;
      };
  included?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preise-page_select".
 */
export interface PreisePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        statPrefix?: T;
        extraStatValue?: T;
        extraStatLabel?: T;
      };
  typesSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        highlightLabel?: T;
        typeLabelPrefix?: T;
        exampleLabel?: T;
        exampleNote?: T;
        buttonLabel?: T;
        buttonLink?: T;
      };
  includedSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        includedLabel?: T;
      };
  paymentSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        amountNote?: T;
      };
  nebenkosten?:
    | T
    | {
        label?: T;
        value?: T;
        note?: T;
        id?: T;
      };
  beispielSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        rowArea?: T;
        rowPricePerSqm?: T;
        rowPurchase?: T;
        rowExtraCosts?: T;
        rowTotal?: T;
        extraCostsRate?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        buttonLabel?: T;
        buttonLink?: T;
        whatsappLabel?: T;
        whatsappUrl?: T;
        note?: T;
      };
  types?:
    | T
    | {
        nr?: T;
        type?: T;
        tag?: T;
        size?: T;
        pricePerSqm?: T;
        units?: T;
        highlight?: T;
        exampleSize?: T;
        examplePrice?: T;
        floorplan?: T;
        features?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  paymentSteps?:
    | T
    | {
        step?: T;
        date?: T;
        label?: T;
        amount?: T;
        note?: T;
        id?: T;
      };
  included?:
    | T
    | {
        label?: T;
        included?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-page_select".
 */
export interface InvestmentPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        description?: T;
        image?: T;
      };
  warumMontenegro?:
    | T
    | {
        headline?: T;
        description?: T;
        image?: T;
        vorteile?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  steuerDaten?:
    | T
    | {
        label?: T;
        value?: T;
        note?: T;
        id?: T;
      };
  mietRendite?:
    | T
    | {
        headline?: T;
        purchase?: T;
        size?: T;
        pricePerSqm?: T;
        weeklyRate?: T;
        occupancyWeeks?: T;
        annualRent?: T;
        yield?: T;
        appreciationLow?: T;
        appreciationHigh?: T;
      };
  paymentSteps?:
    | T
    | {
        step?: T;
        date?: T;
        label?: T;
        amount?: T;
        note?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        buttonLabel?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lage-page_select".
 */
export interface LagePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subline?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        address?: T;
        mapsLabel?: T;
        mapsUrl?: T;
      };
  erreichbarkeit?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  karte?:
    | T
    | {
        image?: T;
        imageAlt?: T;
        badgeTitle?: T;
        badgeSubline?: T;
        caption?: T;
      };
  distances?:
    | T
    | {
        place?: T;
        distance?: T;
        detail?: T;
        note?: T;
        id?: T;
      };
  highlightsSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        text?: T;
        image?: T;
        id?: T;
      };
  markt?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        note?: T;
      };
  marktPreise?:
    | T
    | {
        label?: T;
        price?: T;
        highlight?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        whatsappLabel?: T;
        whatsappUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontakt-page_select".
 */
export interface KontaktPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
      };
  info?:
    | T
    | {
        email?: T;
        telefon?: T;
        whatsapp?: T;
        adresse?: T;
        officeHours?: T;
      };
  direktkontakt?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineZweiteZeile?: T;
        description?: T;
        labelEmail?: T;
        labelWhatsapp?: T;
        labelAdresse?: T;
      };
  exposeTeaser?:
    | T
    | {
        eyebrow?: T;
        text?: T;
      };
  formular?:
    | T
    | {
        headline?: T;
        subline?: T;
        exposeCheckboxTitle?: T;
        exposeCheckboxText?: T;
        felder?:
          | T
          | {
              label?: T;
              key?: T;
              typ?: T;
              breite?: T;
              platzhalter?: T;
              optionen?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              pflichtfeld?: T;
              id?: T;
            };
        datenschutzText?: T;
        fehlerText?: T;
        buttonSending?: T;
        buttonMitExpose?: T;
        buttonOhneExpose?: T;
        erfolgHeadline?: T;
        erfolgText?: T;
        erfolgLinkLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "architektur-page_select".
 */
export interface ArchitekturPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineZweiteZeile?: T;
        headlineAccent?: T;
        description?: T;
        image?: T;
        architektLabel?: T;
        architektName?: T;
        architektStudio?: T;
      };
  zitat?:
    | T
    | {
        text?: T;
        textAccent?: T;
        autor?: T;
      };
  prinzipien?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        image?: T;
        items?:
          | T
          | {
              nr?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  fassade?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        image?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  materialien?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        image?: T;
        items?:
          | T
          | {
              name?: T;
              use?: T;
              detail?: T;
              id?: T;
            };
      };
  galerie?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              aspect?: T;
              id?: T;
            };
      };
  gebaeude?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        features?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        buttonLabel?: T;
        buttonLink?: T;
        buttonSecondaryLabel?: T;
        buttonSecondaryLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}