/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    'contact-submissions': ContactSubmission;
    'form-configs': FormConfig;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'form-configs': FormConfigsSelect<false> | FormConfigsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('de' | 'en' | 'me' | 'tr')
    | ('de' | 'en' | 'me' | 'tr')[];
  globals: {
    website: Website;
    header: Header;
    footer: Footer;
    homepage: Homepage;
    preisstaffel: Preisstaffel;
    'wohnungen-page': WohnungenPage;
    'preise-page': PreisePage;
    'investment-page': InvestmentPage;
    'lage-page': LagePage;
    'kontakt-page': KontaktPage;
    'ueber-uns-page': UeberUnsPage;
    'architektur-page': ArchitekturPage;
    'impressum-page': ImpressumPage;
    'datenschutz-page': DatenschutzPage;
  };
  globalsSelect: {
    website: WebsiteSelect<false> | WebsiteSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    preisstaffel: PreisstaffelSelect<false> | PreisstaffelSelect<true>;
    'wohnungen-page': WohnungenPageSelect<false> | WohnungenPageSelect<true>;
    'preise-page': PreisePageSelect<false> | PreisePageSelect<true>;
    'investment-page': InvestmentPageSelect<false> | InvestmentPageSelect<true>;
    'lage-page': LagePageSelect<false> | LagePageSelect<true>;
    'kontakt-page': KontaktPageSelect<false> | KontaktPageSelect<true>;
    'ueber-uns-page': UeberUnsPageSelect<false> | UeberUnsPageSelect<true>;
    'architektur-page': ArchitekturPageSelect<false> | ArchitekturPageSelect<true>;
    'impressum-page': ImpressumPageSelect<false> | ImpressumPageSelect<true>;
    'datenschutz-page': DatenschutzPageSelect<false> | DatenschutzPageSelect<true>;
  };
  locale: 'de' | 'en' | 'me' | 'tr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  interesse?: string | null;
  nachricht?: string | null;
  expose?: boolean | null;
  /**
   * Auf welcher Sprachfassung der Website die Anfrage abgeschickt wurde.
   */
  sprache?: ('de' | 'en' | 'me' | 'tr') | null;
  /**
   * Antworten auf Felder, die im Backend zum Formular hinzugefügt wurden.
   */
  weitereAngaben?:
    | {
        feld?: string | null;
        wert?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-configs".
 */
export interface FormConfig {
  id: number;
  /**
   * z.B. "Kontaktformular Deutsch"
   */
  name: string;
  /**
   * Das Formular unter „Forms“, für das diese Einstellungen gelten.
   */
  form?: (number | null) | Form;
  /**
   * Nur noch als Rückfallebene für Formulare ohne Verknüpfung.
   */
  formSlug?: string | null;
  sprache?: ('de' | 'en' | 'sr' | 'ru') | null;
  /**
   * Leer lassen = Standard-Adresse aus Umgebungsvariable
   */
  benachrichtigungsEmail?: string | null;
  /**
   * Sendet dem Kunden nach der Formularabsendung automatisch eine Antwort
   */
  autoresponderAktiv?: boolean | null;
  /**
   * Verfügbare Variablen: {{name}}, {{email}}
   */
  autoresponderBetreff?: string | null;
  /**
   * Verfügbare Variablen: {{name}}, {{email}}, {{interesse}}, {{nachricht}}
   */
  autoresponderNachricht?: string | null;
  /**
   * Wird an die Bestätigungsmail angehängt. Zum Austauschen einfach eine andere Datei aus der Medien-Bibliothek wählen oder eine neue hochladen. Leer lassen = keine Datei anhängen. Höchstens etwa 15 MB.
   */
  autoresponderAnhang?: (number | null) | Media;
  /**
   * Ist das aus, bekommt jede Anfrage den Anhang — auch ohne gesetztes Häkchen.
   */
  autoresponderNurMitExpose?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'form-configs';
        value: number | FormConfig;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  interesse?: T;
  nachricht?: T;
  expose?: T;
  sprache?: T;
  weitereAngaben?:
    | T
    | {
        feld?: T;
        wert?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-configs_select".
 */
export interface FormConfigsSelect<T extends boolean = true> {
  name?: T;
  form?: T;
  formSlug?: T;
  sprache?: T;
  benachrichtigungsEmail?: T;
  autoresponderAktiv?: T;
  autoresponderBetreff?: T;
  autoresponderNachricht?: T;
  autoresponderAnhang?: T;
  autoresponderNurMitExpose?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Sprachen freigeben und allgemeine Texte pflegen. Die Sprache der Texte wählen Sie oben rechts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website".
 */
export interface Website {
  id: number;
  /**
   * Deutsch ist immer aktiv. Eine weitere Sprache erscheint erst im Sprachumschalter und in Suchmaschinen, wenn sie hier freigegeben ist. Fehlende Übersetzungen zeigen den deutschen Text.
   */
  sprachen?: {
    en?: boolean | null;
    me?: boolean | null;
    tr?: boolean | null;
  };
  seo?: {
    titel?: string | null;
    beschreibung?: string | null;
    ogTitel?: string | null;
    ogBeschreibung?: string | null;
    ogBildAlt?: string | null;
  };
  /**
   * Texte in Bauteilen, die auf mehreren Seiten vorkommen.
   */
  ui?: {
    menueOeffnen?: string | null;
    menueSchliessen?: string | null;
    sprachwahl?: string | null;
    zurueckZurStartseite?: string | null;
    whatsappNachricht?: string | null;
    whatsappLabel?: string | null;
    whatsappHinweis?: string | null;
    whatsappAria?: string | null;
    ab?: string | null;
    proQm?: string | null;
    sieSindHier?: string | null;
    grundriss?: string | null;
    sliderBild?: string | null;
    bitteWaehlen?: string | null;
    notFoundEyebrow?: string | null;
    notFoundHeadline?: string | null;
    notFoundText?: string | null;
    notFoundStartseite?: string | null;
    notFoundWohnungen?: string | null;
    notFoundKontakt?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label?: string | null;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  address?: string | null;
  copyright?: string | null;
  legalLinks?:
    | {
        label?: string | null;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Die Preisstaffelung wird separat unter „Preisstaffelung" gepflegt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    headline?: string | null;
    subline?: string | null;
    description?: string | null;
    primaryButtonLabel?: string | null;
    primaryButtonLink?: string | null;
    secondaryButtonLabel?: string | null;
    secondaryButtonLink?: string | null;
    /**
     * Ersetzt den Bilder-Slider, solange ein Video gewählt ist. MP4 (H.264), ohne Ton, möglichst unter 3 MB. Gilt für alle Sprachen.
     */
    video?: (number | null) | Media;
    /**
     * Erscheint, bis das Video geladen ist, und bei Besuchern, die „Bewegung reduzieren“ eingestellt haben.
     */
    videoPoster?: (number | null) | Media;
    slides?:
      | {
          image: number | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
    stats?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  lage?: {
    eyebrow?: string | null;
    imageAlt1?: string | null;
    imageAlt2?: string | null;
    imageAlt3?: string | null;
    headline?: string | null;
    text1?: string | null;
    text2?: string | null;
    gallery?:
      | {
          image: number | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Bitte mit der Erreichbarkeitstabelle auf der Lage-Seite abstimmen.
     */
    distances?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  wohnungen?: {
    eyebrow?: string | null;
    detailsLabel?: string | null;
    headline?: string | null;
    types?:
      | {
          type?: string | null;
          tag?: string | null;
          units?: string | null;
          size?: string | null;
          price?: string | null;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    hinweis?: string | null;
  };
  investment?: {
    eyebrow?: string | null;
    linkLabel?: string | null;
    imageAlt?: string | null;
    headline?: string | null;
    text?: string | null;
    /**
     * Nur belegbare Angaben — keine Rendite- oder Wachstumszahlen ohne Quelle.
     */
    stats?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    badgeValue?: string | null;
    badgeLabel?: string | null;
  };
  vertrauen?:
    | {
        icon?: string | null;
        title?: string | null;
        sub?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    buttonLabel?: string | null;
    imageAlt?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    note?: string | null;
  };
  kontakt?: {
    email?: string | null;
    whatsapp?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Erscheint auf der Startseite und auf der Wohnungen-Seite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preisstaffel".
 */
export interface Preisstaffel {
  id: number;
  eyebrow?: string | null;
  headlineStart?: string | null;
  headlineAccent?: string | null;
  headlineEnd?: string | null;
  intro?: string | null;
  stages?:
    | {
        phase?: string | null;
        price?: string | null;
        label?: string | null;
        description?: string | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wohnungen-page".
 */
export interface WohnungenPage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    imageAlt?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  buildingStats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  typesSection?: {
    exampleLabel?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    headlineLine2?: string | null;
    unitsLabel?: string | null;
    priceLabel?: string | null;
    exampleNote?: string | null;
    hinweis?: string | null;
    ctaLabel?: string | null;
  };
  types?:
    | {
        nr?: string | null;
        type?: string | null;
        tag?: string | null;
        size?: string | null;
        terrace?: string | null;
        units?: string | null;
        price?: string | null;
        layout?: string | null;
        description?: string | null;
        exampleSize?: number | null;
        examplePrice?: number | null;
        floorplan?: (number | null) | Media;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  ausstattungSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    hinweis?: string | null;
    premiumTitle?: string | null;
  };
  premiumPaket?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  interiorImages?:
    | {
        image?: (number | null) | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  gebaeude?: {
    imageAlt?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    image?: (number | null) | Media;
  };
  gebaeudeFeatures?:
    | {
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    whatsappNachricht?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
    whatsappLabel?: string | null;
    whatsappUrl?: string | null;
    note?: string | null;
  };
  /**
   * Keine Markennamen als Zusage verwenden. Das Symbol bitte über das Feld „Symbol“ wählen — es gilt für alle Sprachen. Ohne Auswahl richtet es sich nach deutschen Stichworten im Titel (Armatur/Bad, Klima, Eurocode/Erdbeben, Stein, Holz, Schlüssel), in Übersetzungen nach der Position der Kachel.
   */
  ausstattung?:
    | {
        icon?: ('armatur' | 'klima' | 'erdbeben' | 'stein' | 'holz' | 'schluessel') | null;
        brand?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preise-page".
 */
export interface PreisePage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    statPrefix?: string | null;
    extraStatValue?: string | null;
    extraStatLabel?: string | null;
  };
  typesSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    highlightLabel?: string | null;
    typeLabelPrefix?: string | null;
    exampleLabel?: string | null;
    exampleNote?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
    areaNote?: string | null;
  };
  includedSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    includedLabel?: string | null;
    footnote?: string | null;
  };
  paymentSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    amountNote?: string | null;
  };
  nebenkosten?:
    | {
        label?: string | null;
        value?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  beispielSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    rowArea?: string | null;
    rowPricePerSqm?: string | null;
    rowPurchase?: string | null;
    rowExtraCosts?: string | null;
    rowTotal?: string | null;
    /**
     * Nebenkosten = Kaufpreis × Satz, auf volle 10 € gerundet. Gesamt = Kaufpreis + Nebenkosten.
     */
    extraCostsRate?: number | null;
  };
  cta?: {
    whatsappNachricht?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
    whatsappLabel?: string | null;
    whatsappUrl?: string | null;
    note?: string | null;
  };
  types?:
    | {
        nr?: string | null;
        type?: string | null;
        tag?: string | null;
        size?: string | null;
        pricePerSqm?: string | null;
        units?: string | null;
        highlight?: boolean | null;
        exampleSize?: number | null;
        examplePricePerSqm?: number | null;
        /**
         * Weicht der Wert von Fläche × Preis/m² ab, wird er automatisch mit „≈" angezeigt. Wird auch als „ab"-Preis im Hero verwendet.
         */
        examplePrice?: number | null;
        exampleExtraNote?: string | null;
        floorplan?: (number | null) | Media;
        features?:
          | {
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  paymentSteps?:
    | {
        step?: string | null;
        date?: string | null;
        label?: string | null;
        amount?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        label?: string | null;
        included?: boolean | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-page".
 */
export interface InvestmentPage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    eyebrow?: string | null;
    imageAlt?: string | null;
    headline?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    kennzahlen?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  warumMontenegro?: {
    eyebrow?: string | null;
    imageAlt?: string | null;
    headline?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    vorteile?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    bildKennzahlen?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  marktdaten?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    /**
     * Höchstens eine Zahl — nur mit belegter Quelle und Jahr (z. B. MONSTAT oder Zentralbank von Montenegro). Leer lassen, dann wird keine Zahl angezeigt.
     */
    kennzahlWert?: string | null;
    kennzahlLabel?: string | null;
    kennzahlText?: string | null;
    /**
     * z. B. „Quelle: MONSTAT, Statistik der Wohnungspreise, 2025". Wird nur zusammen mit einer Kennzahl angezeigt.
     */
    quelle?: string | null;
    zeitleisteTitel?: string | null;
    zeitleiste?:
      | {
          year?: string | null;
          event?: string | null;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  steuerSektion?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    fussnote?: string | null;
  };
  steuerDaten?:
    | {
        hervorheben?: boolean | null;
        label?: string | null;
        value?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Alle Beträge der Beispielrechnung werden aus diesen Feldern berechnet: Kaufpreis = Größe × Preis/m²; Brutto = Wochen × Wochenpreis je Saison; Ertrag vor Steuer = Brutto − Verwaltungsquote − Betriebskosten; Nettoertrag = Ertrag vor Steuer − Steuersatz; Rendite = Nettoertrag ÷ Kaufpreis.
   */
  mietRendite?: {
    eyebrow?: string | null;
    labelHauptsaison?: string | null;
    labelNebensaison?: string | null;
    labelGesamt?: string | null;
    labelVerwaltung?: string | null;
    vorlageSaison?: string | null;
    vorlageGesamt?: string | null;
    vorlageVerwaltung?: string | null;
    rechnerTitel?: string | null;
    zeileKaufpreis?: string | null;
    zeileHauptsaison?: string | null;
    zeileNebensaison?: string | null;
    zeileBrutto?: string | null;
    zeileVerwaltung?: string | null;
    zeileBetrieb?: string | null;
    zeileVorSteuer?: string | null;
    zeileSteuer?: string | null;
    zeileNetto?: string | null;
    zeileRendite?: string | null;
    headline?: string | null;
    description?: string | null;
    size?: number | null;
    pricePerSqm?: number | null;
    hauptsaisonWochen?: number | null;
    hauptsaisonWochenpreis?: number | null;
    nebensaisonWochen?: number | null;
    nebensaisonWochenpreis?: number | null;
    verwaltungQuote?: number | null;
    betriebskosten?: number | null;
    steuersatz?: number | null;
    fussnote?: string | null;
  };
  zahlungsplan?: {
    eyebrow?: string | null;
    headline?: string | null;
    nebenkosten?: string | null;
  };
  paymentSteps?:
    | {
        step?: string | null;
        label?: string | null;
        amount?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    tags?:
      | {
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lage-page".
 */
export interface LagePage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    headline?: string | null;
    subline?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    imageAlt?: string | null;
    address?: string | null;
    mapsLabel?: string | null;
    mapsUrl?: string | null;
  };
  erreichbarkeit?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  karte?: {
    image?: (number | null) | Media;
    imageAlt?: string | null;
    badgeTitle?: string | null;
    badgeSubline?: string | null;
    caption?: string | null;
  };
  distances?:
    | {
        icon?: ('ort' | 'kueste' | 'altstadt' | 'berge' | 'natur') | null;
        place?: string | null;
        distance?: string | null;
        detail?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  highlightsSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
  };
  highlights?:
    | {
        title?: string | null;
        text?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  markt?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    standText?: string | null;
    note?: string | null;
  };
  marktPreise?:
    | {
        label?: string | null;
        price?: string | null;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    whatsappNachricht?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
    whatsappLabel?: string | null;
    whatsappUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontakt-page".
 */
export interface KontaktPage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    imageAlt?: string | null;
    /**
     * Gilt für alle Sprachen. Ohne Bild wird die Terrasse mit Meerblick gezeigt.
     */
    image?: (number | null) | Media;
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
  };
  info?: {
    email?: string | null;
    telefon?: string | null;
    whatsapp?: string | null;
    adresse?: string | null;
    officeHours?: string | null;
  };
  direktkontakt?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineZweiteZeile?: string | null;
    description?: string | null;
    labelEmail?: string | null;
    labelWhatsapp?: string | null;
    labelAdresse?: string | null;
  };
  exposeTeaser?: {
    eyebrow?: string | null;
    text?: string | null;
  };
  formular?: {
    datenschutzLinkWort?: string | null;
    /**
     * Die Felder selbst werden unter „Forms“ gepflegt. Dort lassen sich beliebig viele Formulare anlegen und hier auswählen.
     */
    form?: (number | null) | Form;
    headline?: string | null;
    subline?: string | null;
    exposeCheckboxTitle?: string | null;
    exposeCheckboxText?: string | null;
    /**
     * Wird nur angezeigt, wenn das gewählte Formular keine Checkbox mit dem Namen „datenschutz“ enthält. Das im Feld „Wort, das auf die Datenschutzerklärung verlinkt“ eingetragene Wort wird automatisch verlinkt — in jeder Sprache passend eintragen.
     */
    datenschutzText?: string | null;
    fehlerText?: string | null;
    buttonSending?: string | null;
    buttonMitExpose?: string | null;
    buttonOhneExpose?: string | null;
    erfolgHeadline?: string | null;
    erfolgText?: string | null;
    erfolgLinkLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Keine Personennamen verwenden — Absender ist die Gesellschaft.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ueber-uns-page".
 */
export interface UeberUnsPage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    imageAlt?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  werWirSind?: {
    eyebrow?: string | null;
    headline?: string | null;
    text?: string | null;
    punkte?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  warumBar?: {
    imageAlt?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    text?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
    image?: (number | null) | Media;
  };
  wieWirBauen?: {
    eyebrow?: string | null;
    headline?: string | null;
    text?: string | null;
    punkte?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  kauf?: {
    eyebrow?: string | null;
    headline?: string | null;
    text?: string | null;
    schritte?:
      | {
          step?: string | null;
          title?: string | null;
          amount?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    nebenkosten?: string | null;
  };
  cta?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
    note?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "architektur-page".
 */
export interface ArchitekturPage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    imageAlt?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    headlineZweiteZeile?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    architektLabel?: string | null;
    architektName?: string | null;
    architektStudio?: string | null;
  };
  zitat?: {
    text?: string | null;
    textAccent?: string | null;
    autor?: string | null;
  };
  prinzipien?: {
    imageAlt?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    items?:
      | {
          nr?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  fassade?: {
    imageAlt?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    items?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  materialien?: {
    imageAlt?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    items?:
      | {
          name?: string | null;
          use?: string | null;
          detail?: string | null;
          id?: string | null;
        }[]
      | null;
    hinweis?: string | null;
  };
  galerie?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    images?:
      | {
          image?: (number | null) | Media;
          alt?: string | null;
          aspect?: ('tall' | 'wide' | 'square') | null;
          id?: string | null;
        }[]
      | null;
  };
  gebaeude?: {
    eyebrow?: string | null;
    headline?: string | null;
    stats?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    features?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
    buttonSecondaryLabel?: string | null;
    buttonSecondaryLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum-page".
 */
export interface ImpressumPage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  eyebrow?: string | null;
  headline?: string | null;
  stand?: string | null;
  /**
   * Leerzeile = neuer Absatz · einfacher Zeilenumbruch = neue Zeile (z. B. Anschrift) · Zeile mit „- " am Anfang = Aufzählungspunkt · **Text** = fett · E-Mail-Adressen, Telefonnummern mit „+" (z. B. +382 68 517 873) und Adressen mit https:// werden automatisch verlinkt.
   */
  abschnitte?:
    | {
        titel?: string | null;
        /**
         * Leerzeile = neuer Absatz · einfacher Zeilenumbruch = neue Zeile (z. B. Anschrift) · Zeile mit „- " am Anfang = Aufzählungspunkt · **Text** = fett · E-Mail-Adressen, Telefonnummern mit „+" (z. B. +382 68 517 873) und Adressen mit https:// werden automatisch verlinkt.
         */
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutz-page".
 */
export interface DatenschutzPage {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  eyebrow?: string | null;
  headline?: string | null;
  stand?: string | null;
  /**
   * Leerzeile = neuer Absatz · einfacher Zeilenumbruch = neue Zeile (z. B. Anschrift) · Zeile mit „- " am Anfang = Aufzählungspunkt · **Text** = fett · E-Mail-Adressen, Telefonnummern mit „+" (z. B. +382 68 517 873) und Adressen mit https:// werden automatisch verlinkt.
   */
  abschnitte?:
    | {
        titel?: string | null;
        /**
         * Leerzeile = neuer Absatz · einfacher Zeilenumbruch = neue Zeile (z. B. Anschrift) · Zeile mit „- " am Anfang = Aufzählungspunkt · **Text** = fett · E-Mail-Adressen, Telefonnummern mit „+" (z. B. +382 68 517 873) und Adressen mit https:// werden automatisch verlinkt.
         */
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website_select".
 */
export interface WebsiteSelect<T extends boolean = true> {
  sprachen?:
    | T
    | {
        en?: T;
        me?: T;
        tr?: T;
      };
  seo?:
    | T
    | {
        titel?: T;
        beschreibung?: T;
        ogTitel?: T;
        ogBeschreibung?: T;
        ogBildAlt?: T;
      };
  ui?:
    | T
    | {
        menueOeffnen?: T;
        menueSchliessen?: T;
        sprachwahl?: T;
        zurueckZurStartseite?: T;
        whatsappNachricht?: T;
        whatsappLabel?: T;
        whatsappHinweis?: T;
        whatsappAria?: T;
        ab?: T;
        proQm?: T;
        sieSindHier?: T;
        grundriss?: T;
        sliderBild?: T;
        bitteWaehlen?: T;
        notFoundEyebrow?: T;
        notFoundHeadline?: T;
        notFoundText?: T;
        notFoundStartseite?: T;
        notFoundWohnungen?: T;
        notFoundKontakt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  address?: T;
  copyright?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        subline?: T;
        description?: T;
        primaryButtonLabel?: T;
        primaryButtonLink?: T;
        secondaryButtonLabel?: T;
        secondaryButtonLink?: T;
        video?: T;
        videoPoster?: T;
        slides?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  lage?:
    | T
    | {
        eyebrow?: T;
        imageAlt1?: T;
        imageAlt2?: T;
        imageAlt3?: T;
        headline?: T;
        text1?: T;
        text2?: T;
        gallery?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        distances?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  wohnungen?:
    | T
    | {
        eyebrow?: T;
        detailsLabel?: T;
        headline?: T;
        types?:
          | T
          | {
              type?: T;
              tag?: T;
              units?: T;
              size?: T;
              price?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        hinweis?: T;
      };
  investment?:
    | T
    | {
        eyebrow?: T;
        linkLabel?: T;
        imageAlt?: T;
        headline?: T;
        text?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        badgeValue?: T;
        badgeLabel?: T;
      };
  vertrauen?:
    | T
    | {
        icon?: T;
        title?: T;
        sub?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        buttonLabel?: T;
        imageAlt?: T;
        eyebrow?: T;
        headline?: T;
        description?: T;
        note?: T;
      };
  kontakt?:
    | T
    | {
        email?: T;
        whatsapp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preisstaffel_select".
 */
export interface PreisstaffelSelect<T extends boolean = true> {
  eyebrow?: T;
  headlineStart?: T;
  headlineAccent?: T;
  headlineEnd?: T;
  intro?: T;
  stages?:
    | T
    | {
        phase?: T;
        price?: T;
        label?: T;
        description?: T;
        active?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wohnungen-page_select".
 */
export interface WohnungenPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        imageAlt?: T;
        eyebrow?: T;
        headline?: T;
        description?: T;
        image?: T;
      };
  buildingStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  typesSection?:
    | T
    | {
        exampleLabel?: T;
        eyebrow?: T;
        headline?: T;
        headlineLine2?: T;
        unitsLabel?: T;
        priceLabel?: T;
        exampleNote?: T;
        hinweis?: T;
        ctaLabel?: T;
      };
  types?:
    | T
    | {
        nr?: T;
        type?: T;
        tag?: T;
        size?: T;
        terrace?: T;
        units?: T;
        price?: T;
        layout?: T;
        description?: T;
        exampleSize?: T;
        examplePrice?: T;
        floorplan?: T;
        image?: T;
        id?: T;
      };
  ausstattungSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        hinweis?: T;
        premiumTitle?: T;
      };
  premiumPaket?:
    | T
    | {
        label?: T;
        id?: T;
      };
  interiorImages?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  gebaeude?:
    | T
    | {
        imageAlt?: T;
        eyebrow?: T;
        headline?: T;
        image?: T;
      };
  gebaeudeFeatures?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        whatsappNachricht?: T;
        eyebrow?: T;
        headline?: T;
        description?: T;
        buttonLabel?: T;
        buttonLink?: T;
        whatsappLabel?: T;
        whatsappUrl?: T;
        note?: T;
      };
  ausstattung?:
    | T
    | {
        icon?: T;
        brand?: T;
        label?: T;
        id?: T;
      };
  included?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preise-page_select".
 */
export interface PreisePageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        statPrefix?: T;
        extraStatValue?: T;
        extraStatLabel?: T;
      };
  typesSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        highlightLabel?: T;
        typeLabelPrefix?: T;
        exampleLabel?: T;
        exampleNote?: T;
        buttonLabel?: T;
        buttonLink?: T;
        areaNote?: T;
      };
  includedSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        includedLabel?: T;
        footnote?: T;
      };
  paymentSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        amountNote?: T;
      };
  nebenkosten?:
    | T
    | {
        label?: T;
        value?: T;
        note?: T;
        id?: T;
      };
  beispielSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        rowArea?: T;
        rowPricePerSqm?: T;
        rowPurchase?: T;
        rowExtraCosts?: T;
        rowTotal?: T;
        extraCostsRate?: T;
      };
  cta?:
    | T
    | {
        whatsappNachricht?: T;
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        buttonLabel?: T;
        buttonLink?: T;
        whatsappLabel?: T;
        whatsappUrl?: T;
        note?: T;
      };
  types?:
    | T
    | {
        nr?: T;
        type?: T;
        tag?: T;
        size?: T;
        pricePerSqm?: T;
        units?: T;
        highlight?: T;
        exampleSize?: T;
        examplePricePerSqm?: T;
        examplePrice?: T;
        exampleExtraNote?: T;
        floorplan?: T;
        features?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  paymentSteps?:
    | T
    | {
        step?: T;
        date?: T;
        label?: T;
        amount?: T;
        note?: T;
        id?: T;
      };
  included?:
    | T
    | {
        label?: T;
        included?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-page_select".
 */
export interface InvestmentPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        imageAlt?: T;
        headline?: T;
        description?: T;
        image?: T;
        kennzahlen?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  warumMontenegro?:
    | T
    | {
        eyebrow?: T;
        imageAlt?: T;
        headline?: T;
        description?: T;
        image?: T;
        vorteile?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        bildKennzahlen?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  marktdaten?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        kennzahlWert?: T;
        kennzahlLabel?: T;
        kennzahlText?: T;
        quelle?: T;
        zeitleisteTitel?: T;
        zeitleiste?:
          | T
          | {
              year?: T;
              event?: T;
              note?: T;
              id?: T;
            };
      };
  steuerSektion?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        fussnote?: T;
      };
  steuerDaten?:
    | T
    | {
        hervorheben?: T;
        label?: T;
        value?: T;
        note?: T;
        id?: T;
      };
  mietRendite?:
    | T
    | {
        eyebrow?: T;
        labelHauptsaison?: T;
        labelNebensaison?: T;
        labelGesamt?: T;
        labelVerwaltung?: T;
        vorlageSaison?: T;
        vorlageGesamt?: T;
        vorlageVerwaltung?: T;
        rechnerTitel?: T;
        zeileKaufpreis?: T;
        zeileHauptsaison?: T;
        zeileNebensaison?: T;
        zeileBrutto?: T;
        zeileVerwaltung?: T;
        zeileBetrieb?: T;
        zeileVorSteuer?: T;
        zeileSteuer?: T;
        zeileNetto?: T;
        zeileRendite?: T;
        headline?: T;
        description?: T;
        size?: T;
        pricePerSqm?: T;
        hauptsaisonWochen?: T;
        hauptsaisonWochenpreis?: T;
        nebensaisonWochen?: T;
        nebensaisonWochenpreis?: T;
        verwaltungQuote?: T;
        betriebskosten?: T;
        steuersatz?: T;
        fussnote?: T;
      };
  zahlungsplan?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        nebenkosten?: T;
      };
  paymentSteps?:
    | T
    | {
        step?: T;
        label?: T;
        amount?: T;
        note?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        buttonLabel?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lage-page_select".
 */
export interface LagePageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        subline?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        address?: T;
        mapsLabel?: T;
        mapsUrl?: T;
      };
  erreichbarkeit?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  karte?:
    | T
    | {
        image?: T;
        imageAlt?: T;
        badgeTitle?: T;
        badgeSubline?: T;
        caption?: T;
      };
  distances?:
    | T
    | {
        icon?: T;
        place?: T;
        distance?: T;
        detail?: T;
        note?: T;
        id?: T;
      };
  highlightsSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        text?: T;
        image?: T;
        id?: T;
      };
  markt?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        standText?: T;
        note?: T;
      };
  marktPreise?:
    | T
    | {
        label?: T;
        price?: T;
        highlight?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        whatsappNachricht?: T;
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        whatsappLabel?: T;
        whatsappUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontakt-page_select".
 */
export interface KontaktPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        imageAlt?: T;
        image?: T;
        eyebrow?: T;
        headline?: T;
        description?: T;
      };
  info?:
    | T
    | {
        email?: T;
        telefon?: T;
        whatsapp?: T;
        adresse?: T;
        officeHours?: T;
      };
  direktkontakt?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineZweiteZeile?: T;
        description?: T;
        labelEmail?: T;
        labelWhatsapp?: T;
        labelAdresse?: T;
      };
  exposeTeaser?:
    | T
    | {
        eyebrow?: T;
        text?: T;
      };
  formular?:
    | T
    | {
        datenschutzLinkWort?: T;
        form?: T;
        headline?: T;
        subline?: T;
        exposeCheckboxTitle?: T;
        exposeCheckboxText?: T;
        datenschutzText?: T;
        fehlerText?: T;
        buttonSending?: T;
        buttonMitExpose?: T;
        buttonOhneExpose?: T;
        erfolgHeadline?: T;
        erfolgText?: T;
        erfolgLinkLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ueber-uns-page_select".
 */
export interface UeberUnsPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        imageAlt?: T;
        eyebrow?: T;
        headline?: T;
        description?: T;
        image?: T;
      };
  werWirSind?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        text?: T;
        punkte?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  warumBar?:
    | T
    | {
        imageAlt?: T;
        eyebrow?: T;
        headline?: T;
        text?: T;
        linkLabel?: T;
        linkHref?: T;
        image?: T;
      };
  wieWirBauen?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        text?: T;
        punkte?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  kauf?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        text?: T;
        schritte?:
          | T
          | {
              step?: T;
              title?: T;
              amount?: T;
              text?: T;
              id?: T;
            };
        nebenkosten?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        buttonLabel?: T;
        buttonLink?: T;
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "architektur-page_select".
 */
export interface ArchitekturPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        imageAlt?: T;
        eyebrow?: T;
        headline?: T;
        headlineZweiteZeile?: T;
        headlineAccent?: T;
        description?: T;
        image?: T;
        architektLabel?: T;
        architektName?: T;
        architektStudio?: T;
      };
  zitat?:
    | T
    | {
        text?: T;
        textAccent?: T;
        autor?: T;
      };
  prinzipien?:
    | T
    | {
        imageAlt?: T;
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        image?: T;
        items?:
          | T
          | {
              nr?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  fassade?:
    | T
    | {
        imageAlt?: T;
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        image?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  materialien?:
    | T
    | {
        imageAlt?: T;
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        image?: T;
        items?:
          | T
          | {
              name?: T;
              use?: T;
              detail?: T;
              id?: T;
            };
        hinweis?: T;
      };
  galerie?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              aspect?: T;
              id?: T;
            };
      };
  gebaeude?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        features?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        buttonLabel?: T;
        buttonLink?: T;
        buttonSecondaryLabel?: T;
        buttonSecondaryLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum-page_select".
 */
export interface ImpressumPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  eyebrow?: T;
  headline?: T;
  stand?: T;
  abschnitte?:
    | T
    | {
        titel?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutz-page_select".
 */
export interface DatenschutzPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  eyebrow?: T;
  headline?: T;
  stand?: T;
  abschnitte?:
    | T
    | {
        titel?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}